name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[CI skip]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: adopt
      - name: Build with Maven
        run: mvn package --file pom.xml